Trigger workflow when bot commit

diff --git a/.github/workflows/dev-workflow.yaml b/.github/workflows/dev-workflow.yaml
--- a/.github/workflows/dev-workflow.yaml
+++ b/.github/workflows/dev-workflow.yaml
@@ -9,6 +9,9 @@ on:
       - 'README.fr.md'
       - 'android/fastlane/**'
       - 'ios/fastlane/**'
+concurrency:
+  group: ${{ github.ref }}
+  cancel-in-progress: true
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
@@ -52,10 +55,10 @@ jobs:
   bump_version:
     name: Bump app version using PR labels
     runs-on: ubuntu-latest
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.PTA }}
       - name: Bump version
         uses: apomalyn/bump-version-using-labels@1.3.1
         with:
@@ -75,6 +78,7 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.head_ref }}
+          token: ${{ secrets.PTA }}
       - uses: actions/setup-java@v3
         with:
           distribution: 'adopt'
@@ -100,6 +104,7 @@ jobs:
       - name: Format files in lib and test directories
         run: flutter format lib test
       - name: Commit formatted files
+        id: commit_formatted
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
           file_pattern: "*.dart"
@@ -107,6 +112,13 @@ jobs:
           commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
           commit_message: "[BOT] Applying format."
           add_options: '-u'
+
+      # Fail workflow, because new commit will execute workflow
+      - if: ${{ steps.commit_formatted.outputs.changes_detected == 'true' }}
+        name: Fail workflow if linting commit
+        run: |
+          echo 'Linting applied, running bot commit workflow'
+          exit 1
 
       # Check if the code has any errors/warnings
       - name: Analyze code
@@ -118,13 +130,20 @@ jobs:
 
       # Commit and push the goldens files updated.
       - name: Commit golden files
-        id: commit
+        id: commit_golden
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
           file_pattern: test/*
           commit_user_name: github-actions[bot]
           commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
-          commit_message: "[BOT] Update golden files"
+          commit_message: '[BOT] Update golden files and applying format'
+
+      # Fail workflow, because new commit will execute workflow
+      - if: ${{ steps.commit_golden.outputs.changes_detected == 'true' }}
+        name: Fail workflow if golden commit
+        run: |
+          echo 'Golden files changes commit, running bot commit workflow'
+          exit 1
 
       - name: Upload coverage file
         uses: actions/upload-artifact@v3
