Fail when version change (#802)
* Workflow changes

* Change id position

* Workflow commit version and fail

* Remove commit_version

* Search for yaml

* Add labels to dependabot commit

---------

Co-authored-by: XavierPaquet-Rapold <XavierPaquet-Rapold@users.noreply.github.com>

diff --git a/.github/workflows/dev-workflow.yaml b/.github/workflows/dev-workflow.yaml
--- a/.github/workflows/dev-workflow.yaml
+++ b/.github/workflows/dev-workflow.yaml
@@ -26,6 +26,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: izhangzhihao/delete-comment@master
+        if: ${{ github.event_name == 'pull_request' }}
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           delete_user_name: github-actions[bot]
@@ -55,15 +56,33 @@ jobs:
   bump_version:
     name: Bump app version using PR labels
     runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'pull_request' }}
     steps:
       - uses: actions/checkout@v3
         with:
           token: ${{ secrets.PTA }}
-      - name: Bump version
-        uses: apomalyn/bump-version-using-labels@1.3.1
+      - name: Bump version using labels
+        uses: apomalyn/bump-version-using-labels@v1.5.0
         with:
           file_path: 'pubspec.yaml'
           reference_branch: 'master'
+          commit: 'false'
+      - name: Commit versioned files
+        id: commit_version
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          file_pattern: "*.yaml"
+          commit_user_name: github-actions[bot]
+          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
+          commit_message: "[BOT] Applying version."
+          add_options: '-u'
+
+      # Fail workflow, because new commit will execute workflow
+      - if: ${{ steps.commit_version.outputs.changes_detected == 'true' }}
+        name: Fail workflow if version commit
+        run: |
+          echo 'Version changed, running bot commit workflow'
+          exit 1
   ##############################################################
   # Testing
   ##############################################################
